name: Automated image builds
on:
  schedule:
    - cron: '0 0 * * *'  # Once a day at midnight. 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ubuntu-image dependencies
        run: |
          sudo apt install -y gdisk qemu-user-static wget squashfs-tools
          sudo snap install --classic --channel=latest/edge ubuntu-image

      - name: Fetch submarine
        run: wget -P gadget https://files.tobhe.de/ubuntu/submarine-a64.kpart

      - name: Build desktop
        run: |
           sudo ubuntu-image --verbose classic chromebook-corsola-desktop.yaml
           sudo sgdisk -A 1:or:11f000000000000 ubuntu-24.10-preinstalled-desktop-arm64+corsola.img || true

      - name: Upload images
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ubuntu-24.10-corsola-images
          path: ubuntu-24.10-preinstalled-*-arm64+corsola.img

      - uses: actions/upload-artifact@v4.3.6
        if: always()
        with:
          path: /tmp/ubuntu-image-*/chroot/debootstrap/debootstrap.log
