name: Automated image builds
on:
  schedule:
    - cron: '0 0 * * *'  # Once a day at midnight. 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ubuntu-image dependencies
        run: |
          sudo apt install -y qemu-user-static
          sudo snap install --classic ubuntu-image

      - name: Run ubuntu-image
        run: |
          gpg-agent --daemon --default-cache-ttl 7200
          mkdir build
          sudo ubuntu-image -w build classic chromebook-corsola.yaml

      - name: Upload image
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ubuntu-24.10-preinstall-desktop-arm64+corsola.img
          overwrite: true

      - uses: actions/upload-artifact@v4.3.6
        if: always()
        with:
          path: build/chroot/debootstrap/debootstrap.log
