name: Automated image builds
on:
  schedule:
    - cron: '0 0 * * *'  # Once a day at midnight. 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ubuntu-image dependencies
        run: |
          sudo apt install -y gdisk qemu-user-static wget
          sudo snap install --classic ubuntu-image

      - name: Fetch submarine
        run: wget -P gadget https://files.tobhe.de/ubuntu/submarine-a64.kpart

      - name: Run ubuntu-image
        run: sudo ubuntu-image --verbose classic chromebook-corsola.yaml

      - name: Fix partition flags
        run: sudo sgdisk -A 1:or:11f000000000000 ubuntu-24.10-preinstall-desktop-arm64+corsola.img

      - name: Upload image
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ubuntu-24.10-preinstall-desktop-arm64+corsola.img
          overwrite: true

      - uses: actions/upload-artifact@v4.3.6
        if: always()
        with:
          path: /tmp/ubuntu-image-*/chroot/debootstrap/debootstrap.log
